// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)


import OpenModalController from "./open_modal_controller"
application.register("open-modal", OpenModalController)

import InsertCodeController from "./insert_code_controller"
application.register("insert-code", InsertCodeController)


import RangeInputController from "./range_input_controller"
application.register("range-input", RangeInputController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import TabController from "./tab_controller"
application.register("tab", TabController)
